name: gpt-review

on:
  push:
    branches:
      - feature/github-actions

jobs:
  gpt-review:
    name: gpt-review
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checks-out my repository
        uses: actions/checkout@v4
      - name: get diff
        # TODO: get pr number from branch name
        run: gh pr diff 2 --repo ${{ github.repository }} --color never > diff.txt
