name: gpt-review

on:
  push:
    branches:
      - feature/github-actions

jobs:
  gpt-review:
    name: gpt-review
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checks-out my repository
        uses: actions/checkout@v4
      - name: get diff
        # TODO: get pr number from branch name
        run: gh pr diff 2 --repo ${{ github.repository }} --color never > diff.txt
      - name: python set up
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install library
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -U openai python-dotenv
          deactivate
      - name: review from gpt
        env:
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_API_BASE: ${{ secrets.AZURE_API_BASE }}
          AZURE_API_VERSION: ${{ secrets.AZURE_API_VERSION }}
          AZURE_DEPLOY_MODEL: ${{ secrets.AZURE_DEPLOY_MODEL }}
        run: |
          touch tmp.txt
          source .venv/bin/activate
          python main.py
          deactivate
          rm diff.txt
