name: gpt-review

on:
  pull_request:
    types: ["opened", "synchronize"]
    branches:
      - main

jobs:
  gpt-review:
    name: gpt-review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checks-out my repository
        uses: actions/checkout@v4
      - name: get diff
        run: gh pr diff "${{ github.event.pull_request.number }}" --repo "${{ github.repository }}" --color never > diff.txt
      - name: python set up
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install library
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -U openai python-dotenv
          deactivate
      - name: review from gpt
        env:
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_API_BASE: ${{ secrets.AZURE_API_BASE }}
          AZURE_API_VERSION: ${{ secrets.AZURE_API_VERSION }}
          AZURE_DEPLOY_MODEL: ${{ secrets.AZURE_DEPLOY_MODEL }}
          EXCLUDE_FILES: ${{ vars.EXCLUDE_FILES }}
        run: |
          touch tmp.txt diff_with_line_number.txt
          . .venv/bin/activate
          python main.py
          deactivate
          rm diff.txt diff_with_line_number.txt
      - name: submit review to pull request
        run: "curl -L -X POST -H \"Accept: application/vnd.github+json\" -H \"Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}\" -H \"X-GitHub-Api-Version: 2022-11-28\" \"https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews\" -d \"$(cat tmp.txt)\""
      - name: remove tmp file
        run: rm tmp.txt
